-- CREATE database PizzaParadise_PizzaBestillingsSystem;
--
-- use PizzaParadise_PizzaBestillingsSystem;
-- 
-- CREATE TABLE topping (
--                          id    INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
--                          name  VARCHAR(50) NOT NULL,
--                          price DOUBLE      NOT NULL
-- );
--
-- CREATE TABLE pizza (
--                        id          INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
--                        name        VARCHAR(50)  NOT NULL,
--                        description VARCHAR(255) NOT NULL,
--                        price       DOUBLE       NOT NULL,
--                        toppingId   INT,
--                        FOREIGN KEY (toppingId) REFERENCES topping(id)
-- );
--
-- CREATE TABLE user (
--                       id          INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
--                       name        VARCHAR(50)  NOT NULL,
--                       email       VARCHAR(50)  NOT NULL UNIQUE,
--                       address     VARCHAR(255) NOT NULL,
--                       bonuspoints INT          NOT NULL DEFAULT 0
-- );
--
-- CREATE TABLE ordre (
--                        id         INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
--                        date       DATETIME NOT NULL,
--                        totalprice DOUBLE   NOT NULL,
--                        pizzaid    INT,
--                        userid     INT,
--                        FOREIGN KEY (pizzaid) REFERENCES pizza(id),
--                        FOREIGN KEY (userid)  REFERENCES user(id)
-- );
--
-- INSERT INTO user (email) VALUES ('bobby@gmail.com');
-- INSERT INTO user (name, email, address, bonuspoints) VALUES ('Bob', 'bobby@gmail.com','Bobbystreet', 1);
--
-- UPDATE user SET name = 'Bob', email = 'bobby@gmail.com', address = 'Bobbystreet', bonusPoint = 1;
--
-- ALTER TABLE user
--     CHANGE COLUMN bonuspoints bonusPoint INT NOT NULL DEFAULT 0;
--
-- SELECT * FROM user;
--
-- INSERT INTO pizza (name, description, price) VALUES ('Margherita', 'Classic tomato and cheese', 89.00);
-- INSERT INTO pizza (name, description, price) VALUES ('Pepperoni', 'Tomato, cheese and pepperoni', 109.00);
--
-- insert into ordre (date,totalprice,pizzaid,userid) values (NOW(),23,1,1);
-- insert into ordre (date,totalprice,pizzaid,userid) values (NOW(),50,2,1);
--
-- ALTER TABLE ordre
--
-- SELECT * FROM ordre;
--
-- DELETE FROM ordre WHERE id = 5;
-- DELETE FROM ordre WHERE id = 6;